---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-lamp-demo-db-svc
  namespace: gangaram
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
  selector:
    app: kubernetes-lamp-demo
    tier: backend
  #clusterIP: None
