---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-lamp-demo-web-svc
  namespace: gangaram
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    nodePort: 30000
  selector:
    app: kubernetes-lamp-demo
    tier: frontend
